[package]
name = "recipe-stage0"
version = "0.1.0"
edition.workspace = true

[dependencies]
hashlink = "0.10.0"
marked-yaml = "0.8.0"
# rattler_conda_types = "0.35.0"
rattler_conda_types = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
rattler-build = { workspace = true }
indexmap = { workspace = true }
url = { workspace = true }
pixi_build_types = { workspace = true }

[dev-dependencies]
insta = { version = "1.42.1", features = ["yaml", "redactions", "filters"] }
