recipe:
  name: pixi-build

cache:
  source:
    path: ..
  requirements:
    build:
      - ${{ compiler("rust") }}
    host:
      - xz >=5.0, <6.0
      - if: unix
        then: openssl

  build:
    script:
      - if: unix
        then:
          - export OPENSSL_DIR="$PREFIX"
          - cargo install --locked --root $PREFIX --path crates/pixi-build-cmake --no-track
          - cargo install --locked --root $PREFIX --path crates/pixi-build-python --no-track
          - cargo install --locked --root $PREFIX --path crates/pixi-build-rattler-build --no-track
        else:
          - cargo install --locked --root %PREFIX% --path crates/pixi-build --no-track --bins

outputs:
  - package:
      name: pixi-build-python
      version: "${{ env.get('PIXI_BUILD_PYTHON_VERSION', default='0.1.0dev') }}"

    build:
      files:
        - bin/pixi-build-python
        - bin/pixi-build-python.exe
    tests:
      - script: pixi-build-python --help

  - package:
      name: pixi-build-cmake
      version: "${{ env.get('PIXI_BUILD_CMAKE_VERSION', default='0.1.0dev') }}"
    build:
      files:
        - bin/pixi-build-cmake
        - bin/pixi-build-cmake.exe
    tests:
      - script: pixi-build-cmake --help

  - package:
      name: pixi-build-rattler-build
      version: "${{ env.get('PIXI_BUILD_RATTLER_BUILD_VERSION', default='0.1.0dev') }}"

    build:
      files:
        - bin/pixi-build-rattler-build
        - bin/pixi-build-rattler-build.exe
    tests:
      - script: pixi-build-rattler-build --help
