[workspace]
authors = ["Bas Zalmstra <bas@prefix.dev>"]
channels = ["conda-forge"]
description = "Showcases how to create a simple C++ executable with Pixi"
name = "pixi_build_rust"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]
version = "0.1.0"

# [tasks.start]
# # Start the built executable
# cmd = ".build/bin/sdl_example"
# depends-on = ["build"]

[package]
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
description = "Showcases how to create a simple C++ executable with Pixi"
name = "pixi-build-rust"
version = "0.1.0"


[dependencies]
pixi-build-rust = { path = "." }

[package.build]
backend = { name = "pixi-build-rust", version = "*" }

# [feature.build.dependencies]
# cmake = "3.26.4.*"
# cxx-compiler = "1.5.2.*"
# make = ">=4.3,<5"
# ninja = "1.11.1.*"
