[project]
name = "py-rattler"
description = "Add a short description here"
authors = [
  "Bas Zalmstra <bas@prefix.dev>",
  "Tarun Pratap Singh <pratapsinghtarun9@gmail.com>",
]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
license = "BSD-3-Clause"

[tasks]

[feature.build.dependencies]
python = "*"
maturin = "~=1.2.2"
pip = "~=23.2.1"
rust = "~=1.86.0"

[feature.build.tasks]
build = "PIP_REQUIRE_VIRTUALENV=false maturin develop"
build-release = "PIP_REQUIRE_VIRTUALENV=false maturin develop --release"

[feature.build.target.linux-64.dependencies]
patchelf = "~=0.17.2"

[feature.test.dependencies]
# Python 3.8 is the minimum supported version, so we use that for testing
python = "3.9.*"

ruff = ">=0.12.3,<0.13"
mypy = "~=1.16.1"

pytest = ">=8.4.1,<9"
pytest-asyncio = ">=1.0.0,<2"
pytest-xprocess = ">=1.0.2,<2"
syrupy = "*"


# used in examples
typer = "*"
# for rust-analyzer
rust-src = "~=1.86.0"

[feature.test.pypi-dependencies]
types-networkx = "*"
# boto3 on conda-forge requires python >=3.10
boto3 = "*"

[feature.test.tasks]
test = { cmd = "pytest --doctest-modules", depends-on = ["build"] }


[environments]
test = { features = ["build", "test"], solve-group = "default" }
# docs = ["docs"]
# repl = ["repl"]
build = ["build"]

[dependencies]
# requests = ">=2.32.3,<2.33"
# types-requests = ">=2.32.4.20250611,<2.32.5"
