on:
  push:
    tags:
      - "pixi-build-cmake-v[0-9]+.[0-9]+.[0-9]+"
      - "pixi-build-python-v[0-9]+.[0-9]+.[0-9]+"
      - "pixi-build-rattler-build-v[0-9]+.[0-9]+.[0-9]+"
  pull_request:

name: "Build and publish pixi builds backends as conda packages"

permissions:
  id-token: write
  contents: read

jobs:
  detect_bin:
    runs-on: ubuntu-latest
    outputs:
      bin_name: ${{ steps.extract_bin.outputs.bin_name }}
      version: ${{ steps.extract_bin.outputs.version }}
    steps:
      - name: Extract bin name and version
        id: extract_bin
        run: |
          TAG=${{ github.ref_name }}
          BIN_NAME=$(echo $TAG | cut -d '-' -f1)
          VERSION=$(echo $TAG | cut -d '-' -f2- | sed 's/^v//')
          echo "Detected binary: $BIN_NAME"
          echo "Version: $VERSION"
          echo "bin_name=$BIN_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  rattler-build:
    needs: detect_bin
    env:
      REPO_NAME: "prefix-dev/pixi-build-backends"
      BIN_NAME: ${{ needs.detect_bin.outputs.bin_name }}
      RECIPE_VERSION: ${{ needs.detect_bin.outputs.version }}
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-20.04 }
          - { target: linux-aarch64, os: ubuntu-latest }
          - { target: linux-ppc64le, os: ubuntu-latest }
          - { target: win-64, os: windows-latest }
          # force older macos-13 to get x86_64 runners
          - { target: osx-64, os: macos-13 }
          - { target: osx-arm64, os: macos-14 }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          environments: build-self
      - name: Enable long paths (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          git config --global core.longpaths true
        shell: bash
      - name: Build ${{ env.BIN_NAME }}
        shell: bash
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: "true"
          RATTLER_BUILD_COLOR: "always"
        run: |
          pixi r -e build-self rattler-build build --recipe recipe/${{ env.BIN_NAME }}.yaml --output-dir=$RUNNER_TEMP --target-platform=${{ env.TARGET_PLATFORM }} --experimental --test native
      - name: Upload OSX or Linux packages
        shell: bash
        if: ${{ github.event_name == 'push' && matrix.os != 'windows-latest' && github.repository == env.REPO_NAME }}
        run: |
          for file in "$RUNNER_TEMP"/**/*.conda; do
            echo "Uploading ${file}"
            pixi r -e build-self rattler-build upload prefix -c pixi-build-backends "$file"
          done
      - name: Upload Windows packages
        shell: pwsh
        if: ${{ github.event_name == 'push' && matrix.os == 'windows-latest' && github.repository == env.REPO_NAME }}
        run: |
          Get-ChildItem -Path $env:RUNNER_TEMP -Filter *.conda -Recurse | ForEach-Object {
            Write-Host "Uploading $($_.FullName)"
            pixi r -e build-self rattler-build upload prefix -c pixi-build-backends "$($_.FullName)"
          }
